# Generated by Django 6.0.3 on 2026-03-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='upload',
            field=models.ImageField(default='productos/default.jpg', upload_to='productos/'),
            preserve_default=False,
        ),
    ]
